# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Group all updates into a single pull request
    commit-message:
      prefix: "chore(deps)"
    pull-request-branch-name:
      separator: "-"
    groups:
      all-dependencies: # Defines a group named "all-dependencies"
        patterns:
          - "*" # Correct pattern to match all dependencies in the ecosystem