name: Go

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]  # Trigger also on any tag push
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: github.ref_type != 'tag'  # Skip on tag push
    permissions:
      contents: read
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v5.0.0
    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24.6'
    - name: Build
      run: go build -v ./...

  lint:
    if: github.ref_type != 'tag'  # Skip on tag push
    permissions:
      contents: read
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v5.0.0
    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24.6'
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v8.0.0

  build_container_and_publish:
    if: github.ref_type == 'tag'
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: harrywickham
          password: ${{ secrets.GHCR }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          tags: |
            ghcr.io/harrywickham/particle-tachyon-gps-dbus:latest
            ghcr.io/harrywickham/particle-tachyon-gps-dbus:${{ github.ref_name }}
